# Generated by Django 5.2.1 on 2025-05-14 18:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='animal',
            name='porte',
            field=models.CharField(choices=[('pequeno', 'Pequeno'), ('médio', 'Médio'), ('grande', 'Grande')], max_length=20),
        ),
        migrations.AlterField(
            model_name='animal',
            name='tipo',
            field=models.CharField(choices=[('cachorro', 'Cachorro'), ('gato', 'Gato'), ('outro', 'Outro')], max_length=20),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='tipo_usuario',
            field=models.CharField(choices=[('pessoa', 'Pessoa Física'), ('ong', 'ONG')], max_length=10),
        ),
    ]
