# Generated by Django 5.2.1 on 2025-05-14 18:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_animal_porte_alter_animal_tipo_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='animal',
            name='porte',
            field=models.CharField(choices=[('Pequeno', 'Pequeno'), ('Médio', 'Médio'), ('Grande', 'Grande')], max_length=20),
        ),
        migrations.AlterField(
            model_name='animal',
            name='tipo',
            field=models.CharField(choices=[('Cachorro', 'Cachorro'), ('Gato', 'Gato'), ('Outro', 'Outro')], max_length=20),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='tipo_usuario',
            field=models.CharField(choices=[('PESSOA', 'Pessoa Física'), ('ONG', 'ONG')], max_length=10),
        ),
    ]
